### ISSUE TITLE
FinalRules Datasets

### ISSUE THREAD

**Issue by haiyLiu** [RManLuo/ChatRule#2]
Thank you for your excellent work. Please ask how you obtained the FinalRules datasets in **Reproduce KGC results with mined rules.**

**Comment by RManLuo** [comment]
Thanks for your interest in our works. Please refer to the [rule mining section](https://github.com/RManLuo/ChatRule/tree/master?tab=readme-ov-file#mining-rules-with-chatrule) for generating the rules used for KGC.

**Comment by haiyLiu** [comment]
> Thanks for your interest in our works. Please refer to the [rule mining section](https://github.com/RManLuo/ChatRule/tree/master?tab=readme-ov-file#mining-rules-with-chatrule) for generating the rules used for KGC.

Thank you for your reply. I ran **Mining Rules with ChatRule** section in Readme.md, however I didn't get FinalRules folder. At the same time, there is almost no duplication of data when I check FinalRules and ranked_rules folders.

**Comment by RManLuo** [comment]
After you finish all the process, you will find the final rule at the folder named similar to `ranked_rules/${DATASET}/gpt-3.5-turbo-top-0-f-50-l-10/none/all`. We will remove the duplicated rules during the process. All I have done is to move all the final rules into the `FinalRules` folder for better readability.

**Comment by haiyLiu** [comment]
OK, thank you very much for your explanation!
